### ISSUE TITLE
Support added natively 

### ISSUE THREAD

**Issue by lewisdoesstuff** [catppuccin/bento#1]
Heya! 

I didn't notice that this existed until last night, so I've added the palettes into bento-next natively, replacing the single Catppuccin theme that existed before. 

The guide links to my fork of the upstream Bento, but it may be better to link to my more feature-rich Vue3 fork, [bento-next](https://github.com/lewisdoesstuff/bento-next)

One of the 3 palettes can be selected from the theme dropdown, below the night mode button.

If you'd prefer to keep the link to the upstream fork with theme support, it's probably best to link to the commit after that, adding automatic light/dark mode switching using the location for OpenWeatherMap.

**Comment by unseen-ninja** [comment]
Oh, this is awesome! I'll update my personal instance to bento-next for sure! 
I'll add a section mentioning and linking bento-next on the readme. Generally I'd keep it tied to the “original” version. Which commit are you talking about for that? c:

**Comment by lewisdoesstuff** [comment]
No worries! 

I've just realised I never actually merged the themes branch into master, which includes sunrise/sunset dark mode switching (using the weather location) and changing the tab title from the config. 

I'll get that merged and drop a reply with the commit hash if you'd prefer a static link as opposed to linking to master.

**Comment by lewisdoesstuff** [comment]
Just updated, I'll keep the themes branch around while this still links to it, but you can update this to [b636e7bf7](https://github.com/lewisdoesstuff/Bento/tree/fb636e7bf7) for the version with the changes included.

**Comment by BlueFalconHD** [comment]
Ok! Thanks! I'll take a look when I am free!

**Comment by unseen-ninja** [comment]
Is there a reason to link to that specific commit? Otherwise it might be better to just link to the repo and main branch, no? c:

**Comment by lewisdoesstuff** [comment]
No particular reason, just ensures that the version we link to is always compatible.  
That said, I don't really plan on updating it further, aside from patching a bug if found, so it's not a problem with me if you want to link to master.
